"""MCP resource: access to the last generated health report."""

from typing import Any

from mcp.server.fastmcp import FastMCP

from server.state import get_last_report


def register_last_report(mcp: FastMCP) -> None:
    """Register report://last resource."""

    @mcp.resource(
        "report://last",
        name="Last health report",
        mime_type="application/json",
        description="Last HealthReport generated by generate_report tool.",
    )
    def last_report() -> dict[str, Any]:
        """
        Возвращает последний сохранённый HealthReport.

        Если отчёт ещё не генерировался, возвращает объект с полем
        ``report`` равным None и коротким сообщением.
        """

        report = get_last_report()
        if report is None:
            return {
                "report": None,
                "message": (
                    "No health report available yet. "
                    "Call generate_report(path) to create one."
                ),
            }
        return {"report": report}
